project:
  type: website

website:
  title: "GeraldoPereira21.github.io"
  navbar:
    left:
      - href: "index.html"
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

